### ISSUE TITLE
Add support for [name].config.json by default.

### ISSUE THREAD

**Issue by latin-1** [cosmiconfig/cosmiconfig#246]
See also: https://babeljs.io/docs/en/config-files#root-babelconfigjson-file

**Comment by jrandolf** [comment]
Not sure if we want to support this just because `babel` uses it. We already have a _lot_ of configuration formats in `cosmiconfig`. In honesty, we should be removing rather than adding, but we can't for compatibility.

Looking at more recent projects, there has been a visible shift from JSON formats to `module.config.js` and `module.config.ts`, so I think it's suggestive that we should probably not implement this.

Please consider using `searchPlaces` to implement this feature.
