### ISSUE TITLE
Segmentation fault with 8.2.0

### ISSUE THREAD

**Issue by ybiquitous** [cosmiconfig/cosmiconfig#307]
Hi, I'd like to let me share that v8.2.0 failed with *"Segmentation fault"* on the Stylelint CI. Please see below for details:

- https://github.com/stylelint/stylelint/pull/6893
- https://github.com/stylelint/stylelint/actions/runs/5172437744/jobs/9316786458?pr=6893#step:7:35
  - <img width="437" alt="image" src="https://github.com/cosmiconfig/cosmiconfig/assets/473530/1e143cdd-1335-42cf-ae8f-30fc795c35cd">

Could you please take a look? Thanks.

**Comment by ntwb** [comment]
See also https://github.com/cosmiconfig/cosmiconfig/pull/304#issuecomment-1575977926

**Comment by d-fischer** [comment]
I will look into this as soon as possible after I am off work.

> See also [#304 (comment)](https://github.com/cosmiconfig/cosmiconfig/pull/304#issuecomment-1575977926)

On first sight, the linked comment does not seem to have anything to do with this.

**Comment by d-fischer** [comment]
https://github.com/stylelint/stylelint/issues/6898 has more info on this. It's a bug of a dependency of stylelint, which does not play well with dynamic `import()` and breaks it globally.

Closing because it's not fixable by cosmiconfig and has to be fixed by either said dependency or by stylelint (by removing said dependency).

**Comment by ybiquitous** [comment]
@d-fischer Thanks for the help! 👍🏼

**Comment by d-fischer** [comment]
For reference, if anyone still stumbles upon this issue, this was fixed in `stylelint` 15.7.0.
