### ISSUE TITLE
Log ESM config errors

### ISSUE THREAD

**Issue by dmnsgn** [cosmiconfig/cosmiconfig#312]
https://github.com/cosmiconfig/cosmiconfig/blob/889d3b491b54babf4d816a10a6c6720df5ccd944/src/loaders.ts#L21-L23

If a config.mjs has an error, it will be swallowed and the generic `Error [ERR_REQUIRE_ESM]: require() of ES Module` will be returned instead because the sync loading kicks in.
The solution would be to also try catch loadJsSync and log both errors if they both fail.

**Comment by JacobLey** [comment]
Just got burned by this as well. Was very confusing because I didn't expect `require` to be called on my ESM code at all.

Perhaps alternative is to switch the order loads happen.

Try first to `require` the file. If it rejects on `ERR_REQUIRE_ESM` then fall back on `import`.
Otherwise propagate the load error.

This is similar to how mocha implements it: https://github.com/mochajs/mocha/blob/master/lib/nodejs/esm-utils.js#L56

**Comment by newives** [comment]
Is there any solution plan?
[conventional-changelog](https://github.com/conventional-changelog/commitlint) and [stylelint](https://github.com/stylelint/stylelint) both rely on `cosmiconfig`, when using `export default` esm syntax, an error `ERR_REQUIRE_ESM` will be reported.

**Comment by d-fischer** [comment]
Fixed in the next v9 alpha, to be released some time today.
